"""
evaluate_model.py

Evaluates DeepFake Shield's models (image, text, audio, video) against
labeled test data and produces a confusion matrix + classification report
for each modality you've collected data for — useful for the
"Result & Discussion" section of your project report.

FOLDER STRUCTURE
----------------
Put this script next to app.py, and arrange test data like this. You do NOT
need all four modalities — the script automatically skips any folder that's
empty or missing, and evaluates whatever it finds.

    test_data/
        image/
            real/   (a handful of real photos: .jpg/.jpeg/.png)
            fake/   (a handful of AI-generated/deepfake photos)
        text/
            real/   (.txt files you genuinely wrote yourself)
            fake/   (.txt files generated by ChatGPT/Claude/etc.)
        audio/
            real/   (real voice recordings: .mp3/.wav/.m4a)
            fake/   (AI-generated / cloned voice clips)
        video/
            real/   (real videos: .mp4/.mov/.webm)
            fake/   (deepfake videos)

SETUP
-----
1. Make sure your .env file (same one app.py uses) has HF_API_TOKEN set.
2. Install what this script needs:
       pip install scikit-learn matplotlib opencv-python-headless python-dotenv requests
3. Run it:
       python evaluate_model.py

For each modality with data, it prints a confusion matrix + precision/
recall/F1/accuracy to the terminal, and saves a chart:
confusion_matrix_image.png, confusion_matrix_text.png, etc.
"""

import os
import time
from pathlib import Path
import pandas as pd
import random
import requests
from dotenv import load_dotenv
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import matplotlib.pyplot as plt
from transformers import pipeline as hf_pipeline


load_dotenv()


HF_API_TOKEN = os.environ.get("HF_API_TOKEN", "")
HF_API_URL = "https://router.huggingface.co/hf-inference/models"

# Keep these in sync with app.py
MODELS = {
    "image": "dima806/deepfake_vs_real_image_detection",
    "text": "Hello-SimpleAI/chatgpt-detector-roberta",
    "audio": "MelodyMachine/Deepfake-audio-detection",
}

_audio_pipeline = None
def get_audio_pipeline():
    global _audio_pipeline
    if _audio_pipeline is None:
        print("Loading local audio model (one-time)...")
        _audio_pipeline = hf_pipeline(
            "audio-classification",
            model=MODELS["audio"],
            chunk_length_s=10,
            stride_length_s=2,
        )
    return _audio_pipeline

VIDEO_FRAMES_TO_SAMPLE = 3   # fewer than the live app, to keep batch evaluation quick

TEST_DATA_DIR = Path(__file__).parent / "test_data"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png"}
TEXT_EXTENSIONS = {".txt"}
TEXT_CSV_PATH = TEST_DATA_DIR / "text" / "AI_Human.csv"
TEXT_CSV_SAMPLES_PER_CLASS = 25   # kitne real + kitne fake chahiye (chhota rakho, warna slow hoga)
AUDIO_EXTENSIONS = {".mp3", ".wav", ".m4a", ".ogg"}
VIDEO_EXTENSIONS = {".mp4", ".mov", ".webm", ".avi"}

AUDIO_MIME = {".mp3": "audio/mpeg", ".wav": "audio/wav", ".m4a": "audio/mp4", ".ogg": "audio/ogg"}
IMAGE_MIME = {".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png"}


# ---------------------------------------------------------------------------
# Hugging Face call helper (shared by every modality)
# ---------------------------------------------------------------------------

def query_hf_model(model_name, data=None, json_payload=None, content_type=None, retries=3):
    url = f"{HF_API_URL}/{model_name}"
    headers = {}
    if HF_API_TOKEN:
        headers["Authorization"] = f"Bearer {HF_API_TOKEN}"
    if content_type:
        headers["Content-Type"] = content_type

    for attempt in range(retries):
        try:
            if json_payload is not None:
                response = requests.post(url, headers=headers, json=json_payload, timeout=30)
            else:
                response = requests.post(url, headers=headers, data=data, timeout=30)
        except requests.exceptions.RequestException as exc:
            print(f"    Request failed: {exc}")
            return None

        if response.status_code == 200:
            return response.json()

        if response.status_code == 503:
            try:
                wait_time = min(response.json().get("estimated_time", 5), 15)
            except Exception:
                wait_time = 5
            print(f"    Model warming up, waiting {wait_time}s...")
            time.sleep(wait_time)
            continue

        print(f"    API error {response.status_code}: {response.text[:150]}")
        return None

    return None


def top_label(result):
    if isinstance(result, list) and result and isinstance(result[0], list):
        result = result[0]
    if not isinstance(result, list) or not result:
        return None
    predictions = [p for p in result if isinstance(p, dict) and "label" in p and "score" in p]
    if not predictions:
        return None
    return max(predictions, key=lambda p: p["score"])["label"]


# ---------------------------------------------------------------------------
# Per-modality classifiers — each returns "real", "fake", or None on failure
# ---------------------------------------------------------------------------

def classify_image_bytes(image_bytes, mimetype="image/jpeg"):
    result = query_hf_model(MODELS["image"], data=image_bytes, content_type=mimetype)
    label = top_label(result)
    if label is None:
        return None
    return "fake" if "fake" in label.lower() else "real"


def classify_text(text):
    # RoBERTa jaise models ki ~512 token limit ke andar rakhne ke liye truncate karo
    truncated = " ".join(text.split()[:400])  # ~400 words safely fits under 512 tokens
    result = query_hf_model(
        MODELS["text"],
        json_payload={
            "inputs": truncated,
            "parameters": {"truncation": True, "max_length": 512}
        }
    )
    label = top_label(result)
    if label is None:
        return None
    is_fake = any(k in label.lower() for k in ["fake", "ai", "chatgpt", "gpt"])
    return "fake" if is_fake else "real"


def classify_audio_path(path):
    try:
        import librosa
        audio, sr = librosa.load(str(path), sr=16000, duration=30)
        result = get_audio_pipeline()({"array": audio, "sampling_rate": sr})
    except Exception as exc:
        print(f"    Local audio inference failed: {exc}")
        return None


def classify_video(path):
    import cv2  # imported lazily so image/text/audio-only runs don't need it installed

    capture = cv2.VideoCapture(str(path))
    total_frames = int(capture.get(cv2.CAP_PROP_FRAME_COUNT))
    if total_frames <= 0:
        capture.release()
        return None

    sample_count = min(VIDEO_FRAMES_TO_SAMPLE, total_frames)
    frame_indices = [int(total_frames * i / sample_count) for i in range(sample_count)]

    votes = []
    for idx in frame_indices:
        capture.set(cv2.CAP_PROP_POS_FRAMES, idx)
        success, frame = capture.read()
        if not success:
            continue
        ok, buffer = cv2.imencode(".jpg", frame)
        if not ok:
            continue
        label = classify_image_bytes(buffer.tobytes(), "image/jpeg")
        if label:
            votes.append(label)

    capture.release()

    if not votes:
        return None
    return "fake" if votes.count("fake") >= votes.count("real") else "real"


# ---------------------------------------------------------------------------
# Generic evaluation runner
# ---------------------------------------------------------------------------

def collect_files(folder, extensions):
    if not folder.exists():
        return []
    return [p for p in sorted(folder.iterdir()) if p.suffix.lower() in extensions]


def evaluate_modality(name, extensions, classify_one):
    """classify_one(path) -> 'real' | 'fake' | None"""
    real_dir = TEST_DATA_DIR / name / "real"
    fake_dir = TEST_DATA_DIR / name / "fake"

    real_files = collect_files(real_dir, extensions)
    fake_files = collect_files(fake_dir, extensions)

    if not real_files and not fake_files:
        print(f"\n[{name.upper()}] No test data found in test_data/{name}/ — skipping.")
        return

    print(f"\n{'=' * 60}")
    print(f"EVALUATING: {name.upper()}  ({len(real_files)} real, {len(fake_files)} fake)")
    print("=" * 60)

    y_true, y_pred = [], []

    for path in real_files:
        print(f"  [real] {path.name}", end=" -> ")
        prediction = classify_one(path)
        print(prediction or "FAILED (skipped)")
        if prediction:
            y_true.append("real")
            y_pred.append(prediction)

    for path in fake_files:
        print(f"  [fake] {path.name}", end=" -> ")
        prediction = classify_one(path)
        print(prediction or "FAILED (skipped)")
        if prediction:
            y_true.append("fake")
            y_pred.append(prediction)

    if not y_true:
        print(f"  No successful predictions for {name} — nothing to report.")
        return

    labels = ["real", "fake"]
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    accuracy = accuracy_score(y_true, y_pred)

    print(f"\n--- {name.upper()} CONFUSION MATRIX ---")
    print(f"{'':10s}{'Pred: Real':>12s}{'Pred: Fake':>12s}")
    print(f"{'True Real':10s}{cm[0][0]:>12d}{cm[0][1]:>12d}")
    print(f"{'True Fake':10s}{cm[1][0]:>12d}{cm[1][1]:>12d}")

    print(f"\n--- {name.upper()} CLASSIFICATION REPORT ---")
    print(classification_report(y_true, y_pred, labels=labels, digits=4))
    print(f"Overall Accuracy: {accuracy * 100:.2f}%  |  Samples evaluated: {len(y_true)}")

    save_confusion_chart(cm, accuracy, name)


def save_confusion_chart(cm, accuracy, name):
    fig, ax = plt.subplots(figsize=(5, 4.5))
    im = ax.imshow(cm, cmap="Blues")

    ax.set_xticks([0, 1])
    ax.set_yticks([0, 1])
    ax.set_xticklabels(["Real", "Fake"])
    ax.set_yticklabels(["Real", "Fake"])
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    ax.set_title(f"{name.capitalize()} Model — Confusion Matrix ({accuracy * 100:.1f}% accuracy)")

    for i in range(2):
        for j in range(2):
            color = "white" if cm[i][j] > cm.max() / 2 else "black"
            ax.text(j, i, str(cm[i][j]), ha="center", va="center", color=color, fontsize=14)

    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    filename = f"confusion_matrix_{name}.png"
    fig.savefig(filename, dpi=150)
    plt.close(fig)
    print(f"Saved chart -> {filename}")


# ---------------------------------------------------------------------------
# Modality-specific file readers (turn a path into what classify_one needs)
# ---------------------------------------------------------------------------

def image_classifier(path):
    mimetype = IMAGE_MIME.get(path.suffix.lower(), "image/jpeg")
    return classify_image_bytes(path.read_bytes(), mimetype)

def sample_text_from_csv(csv_path, samples_per_class, chunksize=5000):
    """Bade AI_Human.csv (text, generated) file se balanced sample nikalta hai
    bina poori file load kiye — chunk-by-chunk padhta hai aur enough mil jaane
    par ruk jaata hai."""
    if not csv_path.exists():
        return [], []

    real_texts, fake_texts = [], []

    for chunk in pd.read_csv(csv_path, usecols=["text", "generated"], chunksize=chunksize):
        chunk = chunk.dropna(subset=["text"])
        for _, row in chunk.iterrows():
            text = str(row["text"]).strip()
            if not text:
                continue
            is_fake = int(row["generated"]) == 1
            if is_fake and len(fake_texts) < samples_per_class:
                fake_texts.append(text)
            elif not is_fake and len(real_texts) < samples_per_class:
                real_texts.append(text)

        if len(real_texts) >= samples_per_class and len(fake_texts) >= samples_per_class:
            break

    random.shuffle(real_texts)
    random.shuffle(fake_texts)
    return real_texts, fake_texts


def evaluate_text_from_csv():
    """evaluate_modality() jaisa hi kaam karta hai, bas .txt folders ki jagah
    seedha AI_Human.csv se text padhta hai."""
    real_texts, fake_texts = sample_text_from_csv(TEXT_CSV_PATH, TEXT_CSV_SAMPLES_PER_CLASS)

    if not real_texts and not fake_texts:
        print(f"\n[TEXT] {TEXT_CSV_PATH} nahi mili ya khali hai — skipping.")
        return

    print(f"\n{'=' * 60}")
    print(f"EVALUATING: TEXT (from AI_Human.csv)  ({len(real_texts)} real, {len(fake_texts)} fake)")
    print("=" * 60)

    y_true, y_pred = [], []

    for i, text in enumerate(real_texts):
        print(f"  [real] sample {i}", end=" -> ")
        prediction = classify_text(text)
        print(prediction or "FAILED (skipped)")
        if prediction:
            y_true.append("real")
            y_pred.append(prediction)

    for i, text in enumerate(fake_texts):
        print(f"  [fake] sample {i}", end=" -> ")
        prediction = classify_text(text)
        print(prediction or "FAILED (skipped)")
        if prediction:
            y_true.append("fake")
            y_pred.append(prediction)

    if not y_true:
        print("  No successful predictions for text — nothing to report.")
        return

    labels = ["real", "fake"]
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    accuracy = accuracy_score(y_true, y_pred)

    print(f"\n--- TEXT CONFUSION MATRIX ---")
    print(f"{'':10s}{'Pred: Real':>12s}{'Pred: Fake':>12s}")
    print(f"{'True Real':10s}{cm[0][0]:>12d}{cm[0][1]:>12d}")
    print(f"{'True Fake':10s}{cm[1][0]:>12d}{cm[1][1]:>12d}")

    print(f"\n--- TEXT CLASSIFICATION REPORT ---")
    print(classification_report(y_true, y_pred, labels=labels, digits=4))
    print(f"Overall Accuracy: {accuracy * 100:.2f}%  |  Samples evaluated: {len(y_true)}")

    save_confusion_chart(cm, accuracy, "text")

def text_classifier(path):
    text = path.read_text(encoding="utf-8", errors="ignore").strip()
    if not text:
        return None
    return classify_text(text)


def audio_classifier(path):
    return classify_audio_path(path)


def video_classifier(path):
    return classify_video(path)


def main():
    if not HF_API_TOKEN:
        print("WARNING: HF_API_TOKEN not found in .env — requests will likely fail.\n")

    evaluate_modality("image", IMAGE_EXTENSIONS, image_classifier)
    evaluate_text_from_csv()
    evaluate_modality("audio", AUDIO_EXTENSIONS, audio_classifier)
    evaluate_modality("video", VIDEO_EXTENSIONS, video_classifier)

    print("\nDone. Any confusion_matrix_*.png files saved above are ready to drop into your report.")


if __name__ == "__main__":
    main()